# Generated by Django 2.2.5 on 2022-01-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220104_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='conutry',
            new_name='country',
        ),
    ]
