# Generated by Django 2.2.5 on 2022-01-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220105_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rule',
            new_name='house_rules',
        ),
    ]
